// generated by stringer -type=flateType; DO NOT EDIT

package compressedhandler

import "fmt"

const _flateType_name = "NoneDeflateCompressGzip"

var _flateType_index = [...]uint8{0, 4, 11, 19, 23}

func (i flateType) String() string {
	if i+1 >= flateType(len(_flateType_index)) {
		return fmt.Sprintf("flateType(%d)", i)
	}
	return _flateType_name[_flateType_index[i]:_flateType_index[i+1]]
}
