// generated by stringer -type=TmplName; DO NOT EDIT

package reload

import "fmt"

const _TmplName_name = "IndexAboutLoginCreateSignupThankYouErrorPage"

var _TmplName_index = [...]uint8{0, 5, 10, 15, 21, 27, 35, 44}

func (i TmplName) String() string {
	if i >= TmplName(len(_TmplName_index)-1) {
		return fmt.Sprintf("TmplName(%d)", i)
	}
	return _TmplName_name[_TmplName_index[i]:_TmplName_index[i+1]]
}
